"""empty message

Revision ID: 434d1a90c2d0
Revises: 7e88bbc1942f
Create Date: 2020-12-31 21:24:21.418839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '434d1a90c2d0'
down_revision = '7e88bbc1942f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
